### ISSUE TITLE
README - missing 'cd ..' beween each module install

### ISSUE THREAD

**Issue by cdanger** [clarus-proxy/proxy#6]
Hello, this may sound obvious, but you need to go back to parent directory (`cd ..`) between each module install (git clone + mvn install). The full installation is very repetitive, therefore at some point you start running commands like a dumb robot without paying attention, and you might forget this one, ending up with nested repositories :-(
So the README should be fixed to include this `cd ..` step.

**Comment by hargathor** [comment]
Of course, it make sense. Will correct it with `cd -` which seems more appropriate (to me).
